@baseURL=http://localhost:8080/api
@token=
@addressId=

### Create address
POST {{baseURL}}/user/addresses
Content-Type: application/json
Authorization: Bearer {{token}}

{
    
}

### Get addresses
GET {{baseURL}}/user/addresses?limit=10&page=1
Content-Type: application/json
Authorization: Bearer {{token}}

### Get address
GET {{baseURL}}/user/addresses/{{addressId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Update address
PUT {{baseURL}}/user/addresses/{{addressId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

### Delete address
DELETE {{baseURL}}/user/addresses/{{addressId}}
Content-Type: application/json
Authorization: Bearer {{token}}
