@baseURL=http://localhost:8080/api
@token=

### Get user 
GET {{baseURL}}/users
Content-Type: application/json

### login
POST {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "terry.donk@local.com",
    "password": "UEBzc3dvcmQxMjM="
}

### Register
POST {{baseURL}}/users/register
Content-Type: application/json

{
    "firstName": "Terry",
    "lastName": "Donk",
    "gender": "male",
    "dob": "1990-04-01T02:25:13.413Z",
    "email": "terry.donk@local.com",
    "password": "UEBzc3dvcmQxMjM=",
    "phoneCode": "+60",
    "phoneNumber": "124040101"
}

### Update user
PUT {{baseURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

### Disable user
DELETE {{baseURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "reason": "disable user reason"
}